### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by zirnc** [baulk/baulktar#1]

**Comment by sskras** [comment]
I suggest considering the [Blue Oak Model license 1.0.0](https://spdx.org/licenses/BlueOak-1.0.0.html) (written by the intellectual property lawyer).

It's permissive license which covers I.P. patents, and was designed to be both:
1. readable by a non-law person and 
2. strict enough from the law's point of view.

Story from the license author:
https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html
